//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mult_ecommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ID { get; set; }
        public string Pro_name { get; set; }
        public string Pro_image { get; set; }
        public Nullable<int> Pro_price { get; set; }
        public string Pro_des { get; set; }
        public Nullable<int> Pro_fk_cat { get; set; }
        public Nullable<int> Pro_fk_user { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Tb_user Tb_user { get; set; }
    }
}
