//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mult_ecommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_user()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int ID { get; set; }
        public string U_name { get; set; }
        public string U_email { get; set; }
        public string U_password { get; set; }
        public string U_image { get; set; }
        public string U_contact { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}
